"""manifest.json -> src/shared/CarData.luau"""
import json
import sys

man = json.load(open(sys.argv[1]))
out = sys.argv[2]


def v3(v):
    return "Vector3.new(%.4f, %.4f, %.4f)" % tuple(v)


# chassis id -> (design, variants, neon, first-generation design, its variants).
# The current designs are named after the chassis. The first-generation meshes (short
# codes) stay in the manifest as a fallback until the new FBX is imported in Studio.
PRESETS = {
    "gt1": ("gt1", ["rwA"], False, "mod", ["rwA"]),
    "aeros": ("aeros", [], False, "aer", []),
    "stealth": ("stealth", [], False, "stl", []),
    "nova": ("nova", [], True, "nov", []),
    "neonracer": ("neonracer", [], True, "neo", []),
    "arrow": ("arrow", ["rwA"], False, "hyb", ["rwA"]),
    "falcon": ("falcon", [], False, "fal", []),
    "viper": ("viper", [], False, "vip", []),
    "vortex": ("vortex", [], False, "r88", []),
    "apex": ("apex", ["rwA"], False, "v10", ["rwA"]),
    "aurora": ("aurora", [], False, "aur", []),
    "retro70": ("retro70", [], False, "r70", []),
    "retro90": ("retro90", [], False, "r92", []),
}
ROUND_WHEEL = {"r70", "r88", "retro70", "vortex"}

L = []
L.append("--!nonstrict")
L.append("-- GENERATED by tools/cargen/gen_luau.py from assets/cars/manifest.json. Do not edit by hand.")
L.append("-- Mesh templates live in ReplicatedStorage.CarMeshes (one MeshPart per object name).")
L.append("local D = {}")
L.append("D.Objects = {")
for name, o in sorted(man["objects"].items()):
    L.append('\t["%s"] = { C = %s, S = %s },' % (name, v3(o["c"]), v3(o["s"])))
L.append("}")
L.append("D.Designs = {")
for dn, a in man["anchors"].items():
    L.append('\t["%s"] = {' % dn)
    L.append("\t\tWheels = {")
    for w in a["wheels"]:
        L.append('\t\t\t{ Pos = %s, R = %.4f, W = %.4f, Tyre = "%s" },' % (v3(w["pos"]), w["r"], w["w"], w["tyre"]))
    L.append("\t\t},")
    head = a["head"]
    L.append("\t\tHead = %s," % v3(head))
    L.append("\t\tExhaust = %s," % v3(a["exhaust"]))
    L.append("\t\tEngine = %s," % v3(a["engine"]))
    L.append("\t\tTrail = { %s, %s }," % (v3(a["trail"][0]), v3(a["trail"][1])))
    nn = a["numberNose"]
    L.append("\t\tNumberNose = { Pos = %s, Size = Vector2.new(%.3f, %.3f), Pitch = %.1f }," % (v3(nn["pos"]), nn["size"][0], nn["size"][1], nn["pitch"]))
    ns = a["numberSide"]
    L.append("\t\tNumberSide = { Pos = %s, Size = Vector2.new(%.3f, %.3f) }," % (v3(ns["pos"]), ns["size"][0], ns["size"][1]))
    ug = a["underglow"]
    L.append("\t\tUnderglow = { Pos = %s, Size = Vector2.new(%.3f, %.3f) }," % (v3(ug["pos"]), ug["size"][0], ug["size"][1]))
    cockpit = (head[0], head[1] + 0.03, head[2] - 0.14)
    nose = (0, nn["pos"][1] + 0.3, nn["pos"][2] + 0.9)
    tcam = (0, head[1] + 0.95, head[2] + 1.35)
    steer = (0, head[1] - 0.40, head[2] - 0.74)
    L.append("\t\tCams = { Cockpit = %s, Nose = %s, TCam = %s }," % (v3(cockpit), v3(nose), v3(tcam)))
    L.append('\t\tSteer = { Pos = %s, Kind = "%s" },' % (v3(steer), "round" if dn in ROUND_WHEEL else "modern"))
    if a.get("flap"):
        L.append("\t\tFlap = { %s }," % ", ".join('["%s"] = %s' % (k, v3(v)) for k, v in sorted(a["flap"].items())))
    L.append("\t},")
L.append("}")
L.append("-- chassis id -> design, optional variant parts, neon accent lines, and the first-generation")
L.append("-- design (Old) used until the new meshes are imported")
L.append("D.Presets = {")


def qlist(xs):
    return ", ".join('"%s"' % x for x in xs)


for k, (dn, vars_, neon, old, old_vars) in PRESETS.items():
    L.append('\t%s = { Design = "%s", Variants = { %s }, Neon = %s, Old = "%s", OldVariants = { %s } },' % (k, dn, qlist(vars_), "true" if neon else "false", old, qlist(old_vars)))
L.append("}")
L.append("return D")
open(out, "w").write("\n".join(L) + "\n")
print("wrote", out, len(man["objects"]), "objects")
